#Componer distintas imagenes
version: "3"

#Servicios
services: 
    web:
        container_name: exampleapp
        restart: always
        build: . #va encontrar el dockerfile
        ports: 
            - "5000:3000"
        links: 
            - mongo #enlace de otro container
        volumes: 
            - .:/usr/src/app
    mongo:
        container_name: mymongodatabase
        image: mongo
        ports: 
            - "27018:27017"
        logging: 
            driver: none